# Generated by Django 3.2.5 on 2021-08-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
