# Generated by Django 3.2.5 on 2021-08-05 11:36

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionitem_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='item_image',
            field=models.ImageField(default='default.png', upload_to=auctions.models.get_image_path),
        ),
    ]
