# Generated by Django 3.2.5 on 2021-08-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionitem_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='bid',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
