# Generated by Django 3.2.5 on 2021-08-06 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210806_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='bid',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='auctions.comment'),
        ),
    ]
